---

- name: make dir for openFrameworks
  file: path=/home/pi/openFrameworks/addons/ofxOMXPlayer state=directory mode=0755 owner=pi group=pi

- name: Copy openFrameworks tarball
  copy: src=ofxOmxPlayer-0.9.0-compatible.tar.gz dest=/home/pi/ mode=0644 owner=pi group=pi

- name: untar openframeworks
  shell: sudo -u pi tar xfz /home/pi/ofxOmxPlayer-0.9.0-compatible.tar.gz -C /home/pi/openFrameworks/addons/ofxOMXPlayer --strip-components 1

#- name: build ofxOmxPlayer
#  environment:
#    MAKEFLAGS: "-j4" 
#    PLATFORM_ARCH: "armv7l" 
#    PLATFORM_VARIANT: "raspberry2"
#    OF_ROOT: "/home/pi/openFrameworks"
#  shell: make -C /home/pi/openFrameworks/addons/ofxOMXPlayer/example-basic -j 4

