---

- name: make dir for ofxOMXPlayer
  file: path=/home/pi/openFrameworks/addons/ofxOMXPlayer state=directory mode=0755 owner=pi group=pi

- name: Copy ofxOMXPlayer tarball
  copy: src=ofxOmxPlayer-0.9.0-compatible.tar.gz dest=/home/pi/ mode=0644 owner=pi group=pi

- name: untar ofxOMXPlayer into addons directory
  shell: sudo -u pi tar xfz /home/pi/ofxOmxPlayer-0.9.0-compatible.tar.gz -C /home/pi/openFrameworks/addons/ofxOMXPlayer --strip-components 1

- name: make a symlink for convenience
  shell: sudo -u pi ln -s /home/pi/openFrameworks/addons/ofxOMXPlayer /home/pi/omx
