---

- name: make usb mount dir
  file: path=/mnt/usb state=directory mode=0755 owner=root

- name: Copy vidpi-player binary 
  copy: src=vidpi-player dest=/usr/local/bin/ mode=0755 owner=root

- name: install systemd service file
  copy: src=vidpi-player.service dest=/etc/systemd/system mode=644

- name: enable systemd service
  shell: systemctl enable vidpi-player.service

