---

- name: Update APT package cache and upgrade
  apt: update_cache=yes

- name: Install base packages selection
  apt: pkg={{item}} state=installed
  with_items:
    - wiringpi
    - libfontconfig
    - libcairo2
    - libfreeimage3
    - libboost-filesystem1.55.0

